name: Sync main to staging

on:
  push:
    branches:
      - main

jobs:
  sync-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out staging
        uses: actions/checkout@v2
        with:
          ref: 'staging'

      - name: Merge main into staging
        run: |
          git fetch origin main
          git merge origin/main --allow-unrelated-histories

      - name: Push changes
        run: git push origin HEAD:staging