name: Release Staging to Production

on:
  workflow_dispatch:

jobs:
  sync-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Check out main branch
        uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Merge staging into main
        run: |
          git fetch origin staging
          git merge origin/staging --allow-unrelated-histories
          
      - name: Create release tag
        run: |
          DATE=$(date +'%Y.%m.%d')
          RELEASE_TAG="release-${DATE}"
          git tag -a "${RELEASE_TAG}" -m "Production release ${DATE}"
          git push origin HEAD:main --tags

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: "Production Release ${{ env.RELEASE_TAG }}"
          generate_release_notes: true