name: Scheduled Pull Request from staging to main

on:
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out staging branch
        uses: actions/checkout@v3
        with:
          ref: staging
          fetch-depth: 0

      - name: Create and auto-merge PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.TOKEN }}
          base: main
          branch: staging-auto-pr-${{ github.run_id }}  # Use a unique branch name
          title: "Scheduled PR from staging to main"
          body: "Automatically created and merged."
          merge-method: squash
          auto-merge: true